name: receipt_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # esc_pos_printer: ^4.0.4
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.7
  flutter_svg: ^0.22.0
  pos_printer_manager: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
          weight: 400
        - asset: fonts/CourierPrime-Bold.ttf
          weight: 700

          

  assets:
    - assets/gok.svg
